export interface IProductModel {
    id?: any,
    prodNum?: number,
    prodName?: string,
    reportNo?: number,
    reportName?: string,
    refCost?:string,
    priceA?: any,
    priceB?: number,
    priceC?: number,
    priceD?: number,
    priceE?: number,
    priceF?: number,
    priceG?: number,
    priceH?: number,
    priceI?: number,
    priceJ?: number,
    question1?: number,
    question2?: number,
    question3?: number,
    question4?: number,
    prodType?: number,
    sizeUp?: number,
    sizeDown?: number,
    isActive?: boolean,
    year?: number,
    month?: number,
    unit?: string,
    foodPrice?: number,
    foodCost?:any,
    foodCostPercent?:number,
    categoryId?: number,
    categoryName?: string,
    createdWhen?: any,
    createdBy?: number,
    modifiedWhen?: any,
    modifiedBy?: number,
    concurrencyStamp?: any,
    isEnabled?: boolean,
    reason?:string,
    totalCount?:number
}