interface UserModel {
  avatarBase64?: string;
  birthday?: string;
  fullName?: string;
  gender?: any;
  code?: string;
  concurrencyStamp?: string;
  createdBy?: number;
  createdWhen?: string;
  email?: string;
  id?: number;
  isEnabled?: boolean;
  modifiedBy?: number;
  modifiedWhen?: string;
  normalizedEmail?: string;
  normalizedUserName?: string;
  passWord?: string;
  passwordHash?: string;
  phoneNumber?: string;
  roleId?: number;
  securityStamp?: string;
  storeId?: number;
  userName?: string;
  title?: string;
  position?: string;
  isFirsttime?: boolean;
  storeName?: string;
  isSendMail?: any;
  isSendInApp?: any;
  isSendSMS?: any;
  currencyMode?: number;
  workingHour?: any;
  dob?: any;
  firstName?: any;
  lastName?: any;
  address?: any;
  workplace?: any;
  clients?: any;
  codePosition?: any;
  namePosition?: any;
  titleId?: Number;
}
interface InfoAccountModel {
  id?: number,
  isEnabled?: boolean,
  concurrencyStamp?: string,
  securityStamp?: string,
  createdWhen?: string,
  createdBy?: number,
  modifiedWhen?: string,
  modifiedBy?: number,
  userName?: string,
  passWord?: any,
  fullName?: string,
  code?: string,
  birthday?: any,
  phoneNumber?: any,
  roleId?: any,
  email?: string,
  avatarBase64?: any,
  storeId?: any,
  storeName?: any,
  passwordHash?: string,
  normalizedEmail?: string,
  normalizedUserName?: string,
  isFirsttime?: any,
  title?: string,
  position?: any,
  gender?: boolean,
  isSendMail?: boolean,
  isSendInApp?: boolean,
  isSendSMS?: boolean,
  currencyMode?: number,
  workingHour?: number,
  titleId?: number,
  firstName?: any,
  lastName?: any,
  positionId?: any,
  fireBaseToken?: string,
  staffId?: number
}

interface IPassword {
  password?: string;
  newPassword?: string;
  confirmPassword?: string;
}
